### ISSUE TITLE
no clue how to use call_action (+ xml parser error)

### ISSUE THREAD

**Issue by laundmo** [lukasklein/fritzconnection#2]
hello there,

im currently trying to use this module to gather statistics from my fritzbox

for this im trying to use `res = conn.call_action('WANDSLInterfaceConfig:1', 'GetInfo', fritzboxtr064="NewDownstreamNoiseMargin")`
to get the Noise Margin. im not sure if im using the additional arguments correctly,(since you didn't provide any examples) but another TR-064 project i saw lead me to beliefe that i needed `fritzboxtr064` as the argument key

this leads me to this traceback though:
```
Traceback (most recent call last):  File "c:/Users/lauri/python-projects/graph-ping/test.py", line 6, in <module>
    'GetInfo', fritzboxtr064="NewDownstreamNoiseMargin")
  File "C:\Users\lauri\AppData\Local\Programs\Python\Python37\lib\site-packages\fritzconnection\fritzconnection.py", line 406, in call_action
    return action.execute(**kwargs)
  File "C:\Users\lauri\AppData\Local\Programs\Python\Python37\lib\site-packages\fritzconnection\fritzconnection.py", line 130, in execute
    result = self.parse_response(response.content)
  File "C:\Users\lauri\AppData\Local\Programs\Python\Python37\lib\site-packages\fritzconnection\fritzconnection.py", line 142, in parse_response
    root = etree.fromstring(response)
  File "src\lxml\etree.pyx", line 3222, in lxml.etree.fromstring
  File "src\lxml\parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
  File "src\lxml\parser.pxi", line 1765, in lxml.etree._parseDoc
  File "src\lxml\parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src\lxml\parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: HR line 1 and BODY, line 1, column 162
```

but when i use call_action without any arguments it returns a empty dictionary.

how would i get any of the stats, what arguments to use?

any help appreciated

**Comment by laundmo** [comment]
gonna close this since im pretty sure this isn't the correct repo
